version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5555:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=Gdr3000
      - POSTGRES_DB=GDR

    volumes:
      - gdr_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - gdr_redis_data:/bitnami/redis/data

volumes:
  gdr_pg_data:
  gdr_redis_data: